# This file was generated by update.sh from the fetchCommit uses in default.nix.
# Do not edit this file by hand. Instead, edit default.nix and run update.sh
{
  "797f7dc49e0bc7fab4b57c021cdf68f595e47841" = {
    hash = "0q96nxw7jg9l9zlpa3wkma5xzmgkdnnajapwhgb2fk2ll224rgs1";
    path = "/nix/store/bycb8ydmy9izvvmipl32ji7f0ibdgj2p-source";
  };
}
