# This file was generated by update.sh from the fetchCommit uses in default.nix.
# Do not edit this file by hand. Instead, edit default.nix and run update.sh
{
  "25b1c9ba2ab16bb95ee74666fa761911b8f67cad" = {
    hash = "070xqr1xnfh2ddnid6w3nmzhzf72w4ipkrg8bn65c66pfj47njfy";
    path = "/nix/store/hpx4spsc1h3bkdzrjpim0y5qza832054-source";
  };
}
