# This file was generated by update.sh from the fetchCommit uses in default.nix.
# Do not edit this file by hand. Instead, edit default.nix and run update.sh
{
  "2a34566b67bef34c551f204063faeecc444ae9da" = {
    hash = "0f793iywrwpj1z4jv2ika8rvpa07s5lhrn228hrq2srz9cl7nij5";
    path = "/nix/store/1cbvlk06mf3i64xhfabh5bd5klj22183-source";
  };
}
