version: "3.9"

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16
    shm_size: 2G
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  storage-engine:
    container_name: storage-engine
    hostname: storageengine
    build: ./storage-engine
    ports:
      - 8001:8001
    depends_on:
      - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  jupyter:
    container_name: jupyter
    hostname: jupyter
    image: jupyter/datascience-notebook
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work

  clourflare-producer:
    container_name: clourflare-producer
    hostname: clourflare-producer
    build: ./producers/cloudflare-radar
    depends_on:
      - storage-engine

  ripe-builtin-prod:
    container_name: ripe-builtin-prod
    hostname: ripe-builtin-prod
    build: ./producers/ripe-prod
    depends_on:
      - storage-engine
