version: "3.9"

services:
  ripe-harvester:
    container_name: ripe-harvester
    hostname: ripe-harvester
    build: ./producers/ripe-prod

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16
    shm_size: 512mb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
