title = 'Starlink Thesis'
theme = "hugo-book"

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[module]
[[module.mounts]]
  source = '../../hugo-docs'
  target = 'content'

[params]
  BookSearch = true
  BookToC = true
  BookPortableLinks = true

