name: db-controller

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16
    shm_size: 8G
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  jupyter:
    container_name: jupyter
    image: jupyter/datascience-notebook
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan/

  pgadmin:
    container_name: pgadmin
    image: elestio/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: researcher@hpi.de
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 81
    ports:
      - 81:81

  schema-generator:
    container_name: schema-generator
    build: ./schema-generator

