# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: self-hosted
    env:
      HUGO_VERSION: 0.120.4
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          dpkg -x ${{ runner.temp }}/hugo.deb ${{ runner.temp }}/hugo
          export PATH=$PATH:${{ runner.temp }}/hugo/usr/local/bin
          hugo version
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Page with Hugo
        run: |
          cd ${{ runner.temp }}/docs
          hugo

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated Upload after push to main"
          branch: html
          file_pattern: ${{ runner.temp }}/docs/public/**/*
          repository: .
          commit_user_name: GitHub Actions HTML Bot
          commit_author: Botty <actions@github.com>
          create_branch: true
          disable_globbing: false
          skip_checkout: true
          skip_fetch: true


  
