# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on: push

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  Build:
    runs-on: self-hosted
    env:
      HUGO_VERSION: 0.120.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Test Nix Installation
        run: nix --version

      - name: Build LaTeX Document
        run:
          cd ${{ github.workspace }}

          nix-build # Creates main.pdf in result folder

      - name: Build Website with Hugo
        run: |
          cd ${{ github.workspace }}

          # Put most recent main.pdf in static folder
          rm -f src/hugo-pages/static/main.pdf
          mkdir -p src/hugo-pages/static
          cp result/main.pdf src/hugo-pages/static
          
          # Build the website
          cd src/hugo-pages/
          nix-build # Basically a `hugo` command

      - name: Deploy to branch
        if: github.ref == 'refs/heads/master'
        run: |
          cd ${{ github.workspace }}/src/hugo-pages/

          # Push results to branch "static-html"
          mkdir _temp
          cp -r ../../.git _temp
          cd _temp
          chmod 755 * # Required so that files can be deleted in the end.

          git config user.email "botty@botnet.com"
          git config user.name "Botty the Bot"
          git fetch --all
          git switch static-html
          rm -rf *
          cp -r ../result/* .

          git add .
          git commit -m "Deployment of current website"
          git push