# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Update Nix

on:
  workflow_dispatch:
  schedule:
  - cron: "30 6 * * 1"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  Build:
    runs-on: self-hosted
    steps:
      - name: Remove Leftovers
        run: |
          cd ${{ github.workspace }}
          chmod -R 777 .

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: recursive
      - name: Get Latest Commit Hash Of Nixpkgs
        run: |
          cd nixpkgs

          git clone --quiet --depth 1 https://github.com/NixOS/nixpkgs.git nixpkgs-test
          cd nixpkgs-test
          export LATEST_HASH=$(git rev-parse HEAD)
          cd .. && rm -rf nixpkgs-test

          echo "Latest Hash found: $LATEST_HASH"

          nix-shell -p python3 --command "python3 update-default-nix.py $LATEST_HASH"
          bash ./update.sh

      - name: Commit Result
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.email "botty@botnet.com"
          git config user.name "Botty the Bot"

          git add .
          git commit -m "[Infrastructure] Regular Update for Nixpkgs"
          git push
